#!/usr/bin/env node
/*
 * Fixture/gate tests for tokens.d.ts (generated by scripts/tokens-json.mjs
 * from tokens.json). Run: node scripts/test-types.mjs (wired into
 * deploy.yml). No TypeScript compiler dependency — string assertions
 * only, matching this repo's zero-dep test style.
 *
 * Checks:
 *  1. tokens.d.ts is in sync with tokens.json (regeneration is a no-op).
 *  2. Every core + palette token name from tokens.json appears as a
 *     quoted literal in tokens.d.ts.
 *  3. The documented public type/interface names are all exported.
 *  4. Braces/parens/backticks balance — a dependency-free stand-in for
 *     "this at least parses" without requiring `typescript` installed.
 *  5. package.json wires tokens.d.ts into "types" and "files".
 */

import { readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

let bad = 0;
function expect(label, cond, detail = '') {
  const ok = !!cond;
  console.log(`${ok ? '✓' : '✗'} ${label}${ok ? '' : ` — ${detail}`}`);
  if (!ok) bad++;
}

// 1. Regeneration must be a no-op (tokens.d.ts already reflects tokens.json).
try {
  execFileSync('node', ['scripts/tokens-json.mjs', '--check'], { stdio: 'pipe' });
  expect('tokens.d.ts is in sync with tokens.json (and tokens.json with the CSS)', true);
} catch (e) {
  expect('tokens.d.ts is in sync with tokens.json (and tokens.json with the CSS)', false, e.stdout?.toString() || e.message);
}

expect('tokens.d.ts exists', existsSync('tokens.d.ts'));
const dts = readFileSync('tokens.d.ts', 'utf8');
const tokens = JSON.parse(readFileSync('tokens.json', 'utf8'));

// 2. Every token name from tokens.json must appear as a quoted literal.
const coreNames = Object.keys(tokens.core);
const paletteNames = Object.keys(tokens.palette);
let missing = [];
for (const name of [...coreNames, ...paletteNames]) {
  if (!dts.includes(`'${name}'`)) missing.push(name);
}
expect(
  `all ${coreNames.length + paletteNames.length} token names present as quoted literals`,
  missing.length === 0,
  `missing: ${missing.join(', ')}`
);

// 3. Documented public API surface must exist.
const mustContain = [
  'export type RemarqueCoreToken',
  'export type RemarquePaletteToken',
  'export type RemarqueToken',
  'export type RemarqueCssVar',
  'export type RemarqueTokenType',
  'export interface RemarqueCoreTokenEntry',
  'export interface RemarquePaletteTokenSideValue',
  'export interface RemarquePaletteTokenEntry',
  'export interface RemarqueTokensFile',
  'export interface RemarqueTokenValues',
  "declare module 'remarque-tokens/tokens.json'",
  'export default tokens',
  '`--${RemarqueToken}`',
];
for (const needle of mustContain) {
  expect(`tokens.d.ts contains ${JSON.stringify(needle)}`, dts.includes(needle));
}

// 4. Balance checks — cheap "does this at least parse" signal.
function countChar(str, ch) {
  return str.split(ch).length - 1;
}
expect('braces balance ({ vs })', countChar(dts, '{') === countChar(dts, '}'));
expect('parens balance (( vs ))', countChar(dts, '(') === countChar(dts, ')'));
expect('backtick count is even (template literal types closed)', countChar(dts, '`') % 2 === 0);
expect('no stray "undefined" leaked into generated literals', !dts.includes('undefined'));
expect('no stray "NaN" leaked into generated literals', !dts.includes('NaN'));
expect('starts with the "generated — do not edit" header', /generated from tokens\.json/i.test(dts.slice(0, 400)) && /do not edit/i.test(dts.slice(0, 400)));

// 5. package.json wiring.
const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
expect('package.json "types" points at tokens.d.ts', pkg.types === './tokens.d.ts' || pkg.types === 'tokens.d.ts');
expect('package.json "files" ships tokens.d.ts', Array.isArray(pkg.files) && pkg.files.includes('tokens.d.ts'));
expect('package.json exports "./tokens.d.ts"', !!pkg.exports?.['./tokens.d.ts']);
expect(
  'package.json exports "./tokens.json" carries a "types" condition',
  typeof pkg.exports?.['./tokens.json'] === 'object' && !!pkg.exports['./tokens.json'].types
);

if (bad) {
  console.error(`test-types FAILED — ${bad} check(s) did not pass`);
  process.exit(1);
}
console.log('test-types passed ✓');
