#!/usr/bin/env node
/*
 * Fixture/gate tests for tokens.d.ts and tokens.schema.json (both
 * generated by scripts/tokens-json.mjs from tokens.json). Run:
 * node scripts/test-types.mjs (wired into deploy.yml). No TypeScript
 * compiler dependency — string assertions only for the .d.ts, matching
 * this repo's zero-dep test style; the JSON Schema section uses `ajv`
 * (devDependency, issue #99 — CI-grade schema validation without hand-
 * rolling a validator; `$data` is never used, so the ReDoS advisory
 * affecting older 8.x lines doesn't apply, and the pin is kept current).
 *
 * Checks:
 *  1. tokens.d.ts is in sync with tokens.json (regeneration is a no-op).
 *  2. Every core + palette token name from tokens.json appears as a
 *     quoted literal in tokens.d.ts.
 *  3. The documented public type/interface names are all exported.
 *  4. Braces/parens/backticks balance — a dependency-free stand-in for
 *     "this at least parses" without requiring `typescript` installed.
 *  5. package.json wires tokens.d.ts into "types" and "files".
 *  6. tokens.json validates against tokens.schema.json (ajv, draft
 *     2020-12) — and a mutated clone that violates the schema is
 *     rejected, proving the schema actually constrains the shape.
 *  7. tokens.json carries the $schema pointer and the DTCG divergence
 *     note; package.json ships/exports tokens.schema.json.
 */

import { readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
// Ajv's default export only bundles draft-07; tokens.schema.json declares
// itself draft 2020-12, so the dedicated 2020 build is required (bare
// `import Ajv from 'ajv'` throws "no schema with key or ref ...2020-12").
import Ajv2020 from 'ajv/dist/2020.js';

let bad = 0;
function expect(label, cond, detail = '') {
  const ok = !!cond;
  console.log(`${ok ? '✓' : '✗'} ${label}${ok ? '' : ` — ${detail}`}`);
  if (!ok) bad++;
}

// 1. Regeneration must be a no-op (tokens.d.ts already reflects tokens.json).
try {
  execFileSync('node', ['scripts/tokens-json.mjs', '--check'], { stdio: 'pipe' });
  expect('tokens.d.ts is in sync with tokens.json (and tokens.json with the CSS)', true);
} catch (e) {
  expect('tokens.d.ts is in sync with tokens.json (and tokens.json with the CSS)', false, e.stdout?.toString() || e.message);
}

expect('tokens.d.ts exists', existsSync('tokens.d.ts'));
const dts = readFileSync('tokens.d.ts', 'utf8');
const tokens = JSON.parse(readFileSync('tokens.json', 'utf8'));

// 2. Every token name from tokens.json must appear as a quoted literal.
const coreNames = Object.keys(tokens.core);
const paletteNames = Object.keys(tokens.palette);
let missing = [];
for (const name of [...coreNames, ...paletteNames]) {
  if (!dts.includes(`'${name}'`)) missing.push(name);
}
expect(
  `all ${coreNames.length + paletteNames.length} token names present as quoted literals`,
  missing.length === 0,
  `missing: ${missing.join(', ')}`
);

// 3. Documented public API surface must exist.
const mustContain = [
  'export type RemarqueCoreToken',
  'export type RemarquePaletteToken',
  'export type RemarqueToken',
  'export type RemarqueCssVar',
  'export type RemarqueTokenType',
  'export interface RemarqueCoreTokenEntry',
  'export interface RemarquePaletteTokenSideValue',
  'export interface RemarquePaletteTokenEntry',
  'export interface RemarqueTokensFile',
  'export interface RemarqueTokenValues',
  "declare module 'remarque-tokens/tokens.json'",
  'export default tokens',
  '`--${RemarqueToken}`',
];
for (const needle of mustContain) {
  expect(`tokens.d.ts contains ${JSON.stringify(needle)}`, dts.includes(needle));
}

// 4. Balance checks — cheap "does this at least parse" signal.
function countChar(str, ch) {
  return str.split(ch).length - 1;
}
expect('braces balance ({ vs })', countChar(dts, '{') === countChar(dts, '}'));
expect('parens balance (( vs ))', countChar(dts, '(') === countChar(dts, ')'));
expect('backtick count is even (template literal types closed)', countChar(dts, '`') % 2 === 0);
expect('no stray "undefined" leaked into generated literals', !dts.includes('undefined'));
expect('no stray "NaN" leaked into generated literals', !dts.includes('NaN'));
expect('starts with the "generated — do not edit" header', /generated from tokens\.json/i.test(dts.slice(0, 400)) && /do not edit/i.test(dts.slice(0, 400)));

// 5. package.json wiring.
const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
expect('package.json "types" points at tokens.d.ts', pkg.types === './tokens.d.ts' || pkg.types === 'tokens.d.ts');
expect('package.json "files" ships tokens.d.ts', Array.isArray(pkg.files) && pkg.files.includes('tokens.d.ts'));
expect('package.json exports "./tokens.d.ts"', !!pkg.exports?.['./tokens.d.ts']);
expect(
  'package.json exports "./tokens.json" carries a "types" condition',
  typeof pkg.exports?.['./tokens.json'] === 'object' && !!pkg.exports['./tokens.json'].types
);
expect('package.json "files" ships tokens.schema.json', Array.isArray(pkg.files) && pkg.files.includes('tokens.schema.json'));
expect('package.json exports "./tokens.schema.json"', pkg.exports?.['./tokens.schema.json'] === './tokens.schema.json');

// 6. tokens.json carries the $schema pointer + the DTCG divergence note
// (issue #99, ratified option ii) — these live IN the generated artifact,
// not just in prose, so they can't be lost on regeneration.
expect('tokens.json has a "$schema" pointer', typeof tokens.$schema === 'string' && tokens.$schema.endsWith('/tokens.schema.json'));
const dtcg = tokens.$extensions?.remarque?.dtcg;
expect(
  'tokens.json $extensions.remarque.dtcg documents the divergence note',
  typeof dtcg?.conformance === 'string' && Array.isArray(dtcg?.divergences) && dtcg.divergences.length >= 2 && typeof dtcg?.note === 'string'
);
expect(
  'DTCG divergence note names both known divergences (color encoding, multi-mode nesting)',
  dtcg?.divergences?.some((d) => /color/i.test(d.aspect)) && dtcg?.divergences?.some((d) => /mode|theme/i.test(d.aspect))
);

// 7. tokens.schema.json — real JSON-Schema validation of tokens.json
// against its own generated schema (ajv, draft 2020-12), plus a negative
// fixture proving the schema is not vacuously permissive.
expect('tokens.schema.json exists', existsSync('tokens.schema.json'));
const schema = JSON.parse(readFileSync('tokens.schema.json', 'utf8'));
expect('tokens.schema.json declares itself draft 2020-12', schema.$schema === 'https://json-schema.org/draft/2020-12/schema');

const ajv = new Ajv2020({ strict: true, allErrors: true });
const validate = ajv.compile(schema);

const validOk = validate(tokens);
expect(
  'tokens.json validates against tokens.schema.json',
  validOk,
  JSON.stringify(validate.errors)
);

// Negative fixture 1: an unknown top-level extension key must be rejected
// (additionalProperties: false on $extensions.remarque) — proves the
// schema actually constrains the shape rather than accepting anything.
const brokenExtraKey = structuredClone(tokens);
brokenExtraKey.$extensions.remarque.unexpectedField = 'should not validate';
expect('mutated fixture (unknown $extensions.remarque key) is REJECTED by the schema', validate(brokenExtraKey) === false);

// Negative fixture 2: an invalid $type enum value on a real core token
// must be rejected.
const brokenType = structuredClone(tokens);
const firstCoreName = Object.keys(brokenType.core)[0];
brokenType.core[firstCoreName].$type = 'not-a-real-type';
expect(`mutated fixture ($type: "not-a-real-type" on --${firstCoreName}) is REJECTED by the schema`, validate(brokenType) === false);

// Negative fixture 3: a palette entry missing its required "dark" side
// must be rejected.
const brokenPalette = structuredClone(tokens);
const firstPaletteName = Object.keys(brokenPalette.palette)[0];
delete brokenPalette.palette[firstPaletteName].dark;
expect(`mutated fixture (missing "dark" on --${firstPaletteName}) is REJECTED by the schema`, validate(brokenPalette) === false);

if (bad) {
  console.error(`test-types FAILED — ${bad} check(s) did not pass`);
  process.exit(1);
}
console.log('test-types passed ✓');
